name: 'Auto Changelog'
description: 'Automatic Changelog generator'
author: 'Ardalan Amini'
branding:
  icon: 'clock'
  color: 'blue'
inputs:
  token:
    description: 'Github token'
    required: true
  exclude:
    description: 'Exclude selected commit types (comma separated)'
    required: false
    default: ''
  file:
    description: 'Specify a change log file to create or update with the latest log. Omit to not write to any file'
    required: false
outputs:
  changelog:
    description: 'The generated changelogs'
runs:
  using: 'node12'
  main: 'action/index.js'
