name: 'Auto Changelog'

description: 'Automatic Changelog generator'

author: 'Ardalan Amini'

branding:
  icon: 'clock'
  color: 'blue'

inputs:

  token:
    description: 'Github token'
    required: true
    default: ${{ github.token }}

  commit-types:
    description: 'Commit types'
    required: false
    default: |
      breaking: Breaking Changes
      feat: New Features
      fix: Bug Fixes
      revert: Reverts
      perf: Performance Improvements
      refactor: Refactors
      deps: Dependencies
      docs: Documentation Changes
      style: Code Style Changes
      build: Build System
      ci: Continuous Integration
      test: Tests
      chore: Chores
      other: Other Changes

  default-commit-type:
    description: 'Default commit type to be used when the commit message matches none of the defined types'
    required: false
    default: 'Other Changes'

outputs:

  changelog:
    description: 'The generated changelogs'

runs:
  using: 'node16'
  main: 'action/index.js'
