name: Auto Changelog

description: Automatic Changelog generator

author: Ardalan Amini

branding:
  icon: clock
  color: blue

inputs:

  github-token:
    description: Github token
    required: true
    default: ${{ github.token }}

  commit-types:
    description: Commit types
    required: true
    default: |
      breaking: Breaking Changes
      feat: New Features
      fix: Bug Fixes
      revert: Reverts
      perf: Performance Improvements
      refactor: Refactors
      deps: Dependencies
      docs: Documentation Changes
      style: Code Style Changes
      build: Build System
      ci: Continuous Integration
      test: Tests
      chore: Chores
      other: Other Changes

  default-commit-type:
    description: Default commit type to be used when the commit message matches none of the defined types
    required: true
    default: Other Changes

  release-name:
    description: Release name (version)
    required: true
    default: ${{ github.ref_name }}

  mention-authors:
    description: Mention the author of each commit
    required: true
    default: 'true'

  mention-new-contributors:
    description: Mention new contributors at the bottom of the changelog (New Contributors)
    required: true
    default: 'true'

  include-compare:
    description: Include GitHub compare at the bottom of the changelog (Full Changelog)
    required: true
    default: 'true'

  semver:
    description: Enable semver based version comparison
    required: true
    default: 'true'

outputs:

  changelog:
    description: The generated changelogs

  prerelease:
    description: Indicates whether it's a pre-release or not (if semver is set to true, otherwise this output will always return false)

  release-id:
    description: The pre-release id in case of prerelease being true, latest otherwise (if semver is set to true, otherwise this output will always return latest)

runs:
  using: node16
  main: action/index.js
