name: 'Auto Changelog'
description: 'Automatic Changelog generator'
author: 'Ardalan Amini'
branding:
  icon: 'clock'
  color: 'blue'
inputs:
  token:
    description: 'Github token'
    required: true
  exclude:
    description: 'Exclude selected commit types (comma separated)'
    required: false
    default: ''
  updateFile:
    description: 'Set to true if a CHANGELOG.md is to be generated/updated'
    required: false
    default: false
  changeLogFilePath:
    description: 'Specify the path of the change log filefor updating if updateFile is set to true'
    required: false
    default: './CHANGELOG.md'
  fileHeading:
    description: 'Specify the markdown text to use as the file heading'
    required: false
    default: '# Changelog'
  sectionHeading:
    description: 'Specify the tagged markdown text to use for each release section'
    required: false
    default: '## Release {{ GITHUB_REF }}'
outputs:
  changelog:
    description: 'The generated changelogs'
runs:
  using: 'node12'
  main: 'action/index.js'
